version: '3.7'

services:

# website
  web:
    build: .
    container_name: web_service_rest
    command: python manage.py runserver 0:8000
    ports:
      - "8002:8000"
    env_file:
      - .web_env.dev
    depends_on:
      - db


# database
  db:
    image: postgres:12.1-alpine
    container_name: db_service_rest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5434"
    env_file:
      - .db_env.dev

volumes:
  postgres_data:
    name: db_data